const GET_BANNER = 'GET_BANNER'
const GET_COUNTDOWN = 'GET_COUNTDOWN'
const GET_HOME = 'GET_HOME'
const GET_MAINNAV = 'GET_MAINNAV'
const GET_MAINCONTENT = 'GET_MAINCONTENT'
const GET_LISTNAV = 'GET_LISTNAV'
const GET_LISTCONTENT = 'GET_LISTCONTENT'
const GET_DETAIL = 'GET_DETAIL'
const GET_MERCHANT = 'GET_MERCHANT'
const GET_PRODUCT = 'GET_PRODUCT'
const GET_SHOPS = 'GET_SHOPS'
const FOOTER_FLAG_CHANGE = 'FOOTER_FLAG_CHANGE'

const LOGIN_USER = 'LOGIN_USER'
const REGISTER_USER = 'REGISTER_USER'
const LOGOUT_USER = 'LOGOUT_USER'
const LOGIN_USERNAME = 'LOGIN_USERNAME'
const GET_CARS = 'GET_CARS'
export {
  GET_BANNER,
  GET_COUNTDOWN,
  GET_HOME,
  GET_MAINNAV,
  GET_MAINCONTENT,
  GET_LISTNAV,
  GET_LISTCONTENT,
  GET_DETAIL,
  GET_MERCHANT,
  GET_PRODUCT,
  GET_SHOPS,
  FOOTER_FLAG_CHANGE,
  REGISTER_USER,
  LOGIN_USER,
  GET_CARS,
  LOGOUT_USER,
  LOGIN_USERNAME
}