
const GET_BANNER = 'GET_BANNER'
const GET_COUNTDOWN = 'GET_COUNTDOWN'
const GET_HOME = 'GET_HOME'
const GET_MAINNAV = 'GET_MAINNAV'
const GET_MAINCONTENT = 'GET_MAINCONTENT'
export {
  GET_BANNER,GET_COUNTDOWN,GET_HOME,GET_MAINNAV,GET_MAINCONTENT
}